from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('beneficios/', views.beneficios, name='beneficios'),
    path('journaling/', views.journaling, name='journaling'),
    path('journaling_delhes/', views.journaling_delhes, name='journaling_delhes'),
    path('journaling_data/', views.journaling_data, name='journaling_data'),
    path('informacoes/', views.informacoes, name='informacoes'),
    path('testemunhos/', views.testemunhos, name='testemunhos'),
    path('q&a/', views.qa, name='q&a'),
    path('pacientes/', views.inicio_psi, name='pacientes'),
    path('pac_indiv/<int:paciente_id>/', views.paciente_detail, name='pac_indiv'),
    path('atualizar_cor_resposta/', views.atualizar_cor_resposta, name='atualizar_cor_resposta'),
    path('reverter_cores_originais/', views.reverter_cores_originais, name='reverter_cores_originais'),
    path('avaliar_resposta_oncologica/', views.avaliar_resposta_oncologica, name='avaliar_resposta_oncologica'),
    path('register/', views.register_view, name='register'),
    path('enviar-pergunta/', views.enviar_pergunta, name='enviar_pergunta'),
    path('chat/', views.chat, name='chat'),
    path('chat/paciente/', views.chat_paciente_view, name='chat_paciente_view'),
    path('chat/<int:paciente_id>/', views.chat, name='chat_paciente'),
    path('chat/mensagens/<int:conversa_id>/', views.carregar_mensagens, name='carregar_mensagens'),
    path('chat/apagar/<int:conversa_id>/', views.apagar_conversa, name='apagar_conversa'),
    path('chat/enviar/<int:conversa_id>/', views.enviar_mensagem, name='enviar_mensagem'),
    path('chat/marcar-lidas/<int:conversa_id>/', views.marcar_mensagens_lidas, name='marcar_mensagens_lidas'),
    path('chat/unread-count/', views.get_unread_count, name='get_unread_count'),
    path('salvar_testemunho/', views.salvar_testemunho, name='salvar_testemunho'),
    path('editar_testemunho/<int:testemunho_id>/', views.editar_testemunho, name='editar_testemunho'),
    path('apagar_testemunho/<int:testemunho_id>/', views.apagar_testemunho, name='apagar_testemunho'),
    path('meu_perfil/', views.meu_perfil, name='meu_perfil'),
    path('apagar_conta/', views.apagar_conta, name='apagar_conta'),
    path('pergunta/', views.pergunta_aleatoria, name='pergunta_aleatoria'),
    path('toggle_favorito/', views.toggle_favorito, name='toggle_favorito'),
    path('atualizar_status/', views.atualizar_status, name='atualizar_status'),
    path('mapaperucas/', views.mapaperucas, name='mapaperucas'),
    path('alterar_password/', views.alterar_password, name='alterar_password'),
]