# Generated by Django 5.2 on 2025-05-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('telemovel', models.CharField(max_length=15)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='TopicFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopicInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TpPerg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.utilizador')),
                ('data_nascimento', models.DateField()),
                ('estado_pac', models.CharField(max_length=100)),
            ],
            bases=('myapp.utilizador',),
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.utilizador')),
                ('certificado_profissional', models.CharField(max_length=100)),
                ('validade_certificado', models.DateField()),
                ('tipo_profissional', models.CharField(choices=[('PSICOLOGO', 'Psicólogo'), ('MEDICO', 'Médico'), ('ENFERMEIRO', 'Enfermeiro')], max_length=20)),
            ],
            bases=('myapp.utilizador',),
        ),
        migrations.CreateModel(
            name='MsgChatInd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='myapp.utilizador')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='myapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pergunta', models.TextField()),
                ('conteudo', models.TextField()),
                ('publico_npublico', models.BooleanField()),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='PergIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_pergunta', models.DateField()),
                ('publico_npublico', models.BooleanField()),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topicfaq')),
            ],
        ),
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topicinf')),
            ],
        ),
        migrations.CreateModel(
            name='BancoPerg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tpperg')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pacientes', models.ManyToManyField(related_name='enfermidades', to='myapp.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissionais',
            field=models.ManyToManyField(related_name='pacientes', to='myapp.profissionalsaude'),
        ),
    ]
