# Generated by Django 5.2 on 2025-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_cancro',
            field=models.CharField(max_length=100),
        ),
    ]
