# Generated by Django 5.2 on 2025-07-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_paciente_tipo_cancro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
