# Generated by Django 5.2 on 2025-07-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_utilizador_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
