# Generated by Django 5.2 on 2025-07-01 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_utilizador_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTestemunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('visibilidade', models.CharField(choices=[('publico', 'Público'), ('anonimo', 'Anónimo')], max_length=10)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
