# Generated by Django 5.2 on 2025-07-02 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_toptestemunho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'Hospitais'},
        ),
        migrations.AlterField(
            model_name='hospital',
            name='morada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nome',
            field=models.CharField(choices=[('CHULN', 'Centro Hospitalar Universitário Lisboa Norte'), ('CHULC', 'Centro Hospitalar Universitário Lisboa Central'), ('CHULSJ', 'Centro Hospitalar Universitário Lisboa Sul'), ('IPO_LISBOA', 'Instituto Português de Oncologia de Lisboa Francisco Gentil'), ('IPO_PORTO', 'Instituto Português de Oncologia do Porto Francisco Gentil'), ('IPO_COIMBRA', 'Instituto Português de Oncologia de Coimbra Francisco Gentil'), ('CHUC', 'Centro Hospitalar e Universitário de Coimbra'), ('CHP', 'Centro Hospitalar do Porto'), ('CHVNG', 'Centro Hospitalar Vila Nova de Gaia/Espinho'), ('CHTMAD', 'Centro Hospitalar Tâmega e Sousa'), ('CHTS', 'Centro Hospitalar Trás-os-Montes e Alto Douro'), ('CHBA', 'Centro Hospitalar do Baixo Alentejo'), ('CHAL', 'Centro Hospitalar do Algarve'), ('CHLC', 'Centro Hospitalar Leiria-Pombal'), ('CHBV', 'Centro Hospitalar Barreiro Montijo'), ('CHLO', 'Centro Hospitalar de Loures'), ('CHOEIRAS', 'Centro Hospitalar Oeste'), ('CHTM', 'Centro Hospitalar Tondela Viseu'), ('CHUCG', 'Centro Hospitalar Universitário Cova da Beira'), ('CHUCB', 'Centro Hospitalar Universitário do Algarve'), ('HOSPITAL_PRIVADO', 'Hospital Privado'), ('OUTRO', 'Outro')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hospital'),
        ),
    ]
