# Generated by Django 5.2 on 2025-07-02 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_hospital_options_alter_hospital_morada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_cancro',
            field=models.CharField(choices=[('MAMA', 'Cancro da Mama'), ('PULMAO', 'Cancro do Pulmão'), ('COLON', 'Cancro do Cólon/Recto'), ('PROSTATA', 'Cancro da Próstata'), ('PELE', 'Cancro da Pele (Melanoma)'), ('CERVICAL', 'Cancro do Colo do Útero'), ('OVARIO', 'Cancro do Ovário'), ('PANCREAS', 'Cancro do Pâncreas'), ('ESTOMAGO', 'Cancro do Estômago'), ('FIGADO', 'Cancro do Fígado'), ('CEREBRO', 'Cancro do Cérebro'), ('LEUCEMIA', 'Leucemia'), ('LINFOMA', 'Linfoma'), ('MULTIPLO_MIELOMA', 'Múltiplo Mieloma'), ('SARCOMA', 'Sarcoma'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pergunta')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'pergunta')},
            },
        ),
    ]
