# Generated by Django 5.2 on 2025-07-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pergunta_alter_paciente_tipo_cancro_resposta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pergunta',
            new_name='JournPerguntas',
        ),
        migrations.RenameModel(
            old_name='Resposta',
            new_name='JournRespostas',
        ),
    ]
