# Generated by Django 5.2 on 2025-07-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_perguntaresposta_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaresposta',
            name='vezes_feita',
            field=models.IntegerField(default=1),
        ),
    ]
