# Generated by Django 5.2 on 2025-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_perguntaresposta_vezes_feita'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='vezes_feita',
            field=models.IntegerField(default=5),
        ),
    ]
