# Generated by Django 5.2 on 2025-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_faq_vezes_feita'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('AUSENTE', 'Ausente')], default='ONLINE', max_length=20),
        ),
    ]
