# Generated by Django 5.2 on 2025-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_profissionalsaude_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='especialidades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='zona_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
