# Generated by Django 5.2 on 2025-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_profissionalsaude_especialidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='outro_cancer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='outro_hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='n_pacientes',
            field=models.IntegerField(default=0),
        ),
    ]
