# Generated by Django 5.2 on 2025-07-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_hospital_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgchatind',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_mensagem', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='myapp.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='myapp.profissionalsaude')),
            ],
            options={
                'unique_together': {('paciente', 'profissional')},
            },
        ),
        migrations.AddField(
            model_name='msgchatind',
            name='conversa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='myapp.conversa'),
        ),
    ]
