# Generated by Django 5.2 on 2025-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_msgchatind_lida_conversa_msgchatind_conversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='journrespostas',
            name='cor_manual',
            field=models.CharField(blank=True, choices=[('vermelho', 'Vermelho'), ('amarelo', 'Amarelo'), ('verde', 'Verde')], max_length=10, null=True),
        ),
    ]
