# Generated by Django 5.2 on 2025-07-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_journrespostas_cor_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('critico', 'Crítico'), ('moderado', 'Moderado'), ('estavel', 'Estável')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_estados', to='myapp.paciente')),
            ],
        ),
    ]
