# Generated by Django 5.2 on 2025-07-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_journrespostas_data_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journrespostas',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
