# Generated by Django 5.2 on 2025-07-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='hospital',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='password',
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
    ]
