# Generated by Django 5.2 on 2025-07-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='telemovel',
        ),
        migrations.AddField(
            model_name='paciente',
            name='hospital',
            field=models.CharField(default='Lisboa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_cancro',
            field=models.CharField(default='Pele', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilizador',
            name='data_nascimento',
            field=models.DateField(default='2000-11-11'),
            preserve_default=False,
        ),
    ]
