# Generated by Django 5.2 on 2025-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_journrespostas_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='journrespostas',
            name='privacidade',
            field=models.CharField(choices=[('publico', 'Público'), ('anonimo', 'Privado')], default='anonimo', max_length=10),
        ),
    ]
