# Generated by Django 5.2 on 2025-07-02 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_journrespostas_privacidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to=settings.AUTH_USER_MODEL)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'favorito')},
            },
        ),
    ]
