# Generated by Django 5.2 on 2025-07-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_perguntaresposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaresposta',
            name='topico',
            field=models.CharField(default='Outro', max_length=100),
        ),
    ]
