# Generated by Django 5.2 on 2025-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_paciente_outro_cancer_type_paciente_outro_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
