# Generated by Django 5.2 on 2025-07-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_estadopaciente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journrespostas',
            unique_together={('utilizador', 'pergunta', 'data_resposta')},
        ),
    ]
