# Generated by Django 5.2 on 2025-07-15 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_journrespostas_data_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='journrespostas',
            name='data_resposta',
            field=models.DateTimeField(),
        ),
    ]
