# Generated by Django 5.2 on 2025-07-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_utilizador_foto_perfil_and_more'),
        ('myapp', '0029_utilizador_profile_picture_and_more'),
    ]

    operations = [
    ]
