# Generated by Django 5.2 on 2025-07-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_merge_20250721_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='profile_picture',
        ),
    ]
