# Generated by Django 5.2 on 2025-07-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_beneficio_remove_utilizador_foto_perfil_and_more'),
        ('myapp', '0031_beneficios_iniciais'),
    ]

    operations = [
    ]
