# Generated by Django 5.2 on 2025-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_merge_20250721_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
