# Generated by Django 5.2 on 2025-07-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_informacoes_extras_iniciais'),
        ('myapp', '0033_informacaoextra'),
    ]

    operations = [
    ]
